hyperparameters:
  neuron_index: 225
  act_weight: 0.5
  upscaling_factor: 1.5
  upscaling_steps: 10
  optimization_steps: 30

device: cpu

image_dim:
  height: 28
  width: 28

path:
  temp_image_path : temp_images

video:
  repeat_frames: 5
  ext: png
  output_path: output.mp4